name = "HCGeoThermGraphics"
uuid = "52edfbc3-9dbd-449c-90fa-4028de0dba99"
authors = ["Evgeny Cherkashin"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
